name: Build and push a docker container

on:
  # Run whenever there's a push to the 'development' branch
  push:
    branches:
      - development

  # Allow manual triggering from the Actions tab
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  # Adjust this to match your preferred image name
  IMAGE: ghcr.io/${{ github.repository }}/mlops_dtu_2025_project7

jobs:
  build-and-push-docker-image:
    name: Build and push docker image
    runs-on: ubuntu-latest
    permissions:
      contents: read       # needed to checkout code
      packages: write      # needed to push to GHCR
      id-token: write      # (optional) if you need OIDC later, can keep or remove

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for ${{ env.IMAGE }}
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.IMAGE }}
          tags: |
            type=raw,value=latest
            type=sha

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          # Point to the folder containing your code, typically '.'
          context: .
          # Use the custom Dockerfile path
          file: dockerfiles/train.dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
